; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F405RG]
platform = ststm32
board = genericSTM32F405RG
framework = stm32cube
debug_tool = stlink
upload_protocol = stlink
lib_archive = false
test_ignore = test_desktop, test_platform
; Need this to change HCE value in stm32f4xx_hal_config.h
board_build.stm32cube.custom_config_header = yes
build_flags =
  -mfloat-abi=softfp
  -Iinclude
  -mfpu=fpv4-sp-d16 ;Enable floating point extension

[env:test_native]
platform = native
test_build_src = no
build_flags = 
    -D UNITY_INCLUDE_DOUBLE 
    -DUNITY_DOUBLE_PRECISION=1e-12 
    -Iinclude 
    -Ilib/FreeRTOS/src 
    -Ilib/hardware 
    -Ilib/libcontrollers/src
lib_deps =
    FreeRTOS
    cmsis
    stm32cube
test_framework = unity
lib_ignore = FreeRTOS, hardware
test_filter = test_utils, test_commands, test_controller

[env:test_platforms]
platform = native
test_build_src = yes
build_flags = 
    -D UNITY_INCLUDE_DOUBLE 
    -DUNITY_DOUBLE_PRECISION=1e-12 
    -Iinclude 
    -Ilib/FreeRTOS/src 
    -Ilib/hardware 
    -Ilib/libcontrollers/src
lib_deps =
    FreeRTOS
    cmsis
    stm32cube
test_framework = unity
lib_ignore = FreeRTOS, hardware
build_src_filter = +<platform_omni.c> +<platform_mecanum.c> +<platform_differential.c>
test_filter = test_platform_*