# ------------------------------------------------------------
# File name: generator.py
# ------------------------------------------------------------
"""Validate the command schema and generate C, C++, or Markdown output."""
import argparse
import datetime
import json
import os
import re

# Map of type names to their size in bytes
type_to_size_map = {
    "bool": 1,
    "uint8_t": 1,
    "uint16_t": 2,
    "uint32_t": 4,
    "uint64_t": 8,
    "int8_t": 1,
    "int16_t": 2,
    "int32_t": 4,
    "double": 8,
    "integer": 4,
}

def file_header(version, comment_char="//"):
    """Return the generated-file banner with schema version and generation time."""
    return f"""{comment_char} ----------------------------------------------------------------------------
{comment_char} Kinisi motr controller commands.
{comment_char} This file is auto generated by the commands generator from JSON file.
{comment_char} Do not edit this file manually.
{comment_char} Purpose: Protocol message IDs, wire types, and validation helpers.
{comment_char} Timestamp: { datetime.datetime.now().strftime("%Y-%m-%d %H:%M:00") }
{comment_char} Version: {version}
{comment_char} ----------------------------------------------------------------------------\n\n"""

# Function to validate names for various categories like 'Type', 'Command', etc.
# 'name' is the name to be validated, 'category' specifies the category, and 'context' provides additional information.
def validate_name(name, category, context):
    """Return diagnostics for an invalid schema identifier in the supplied context."""
    errors = []
    # Check if the name contains a space
    if " " in name:
        errors.append(f"{category} name '{name}' in {context} contains a space.")
    return errors


# Function to validate a command in the JSON
# 'command' is a dictionary containing the command details
def validate_command(command):
    """Check message direction, response direction, field names, and declared ranges."""
    errors = []
    directions = {'client_to_controller', 'controller_to_client'}
    direction = command.get('direction')
    if direction not in directions:
        errors.append(f"Command '{command['command']}' must declare direction as client_to_controller or controller_to_client.")
    if 'response' in command:
        response_direction = command['response'].get('direction')
        if response_direction not in directions or response_direction == direction:
            errors.append(f"Response for '{command['command']}' must declare the opposite direction to its command.")
    # Validate the name of the command
    errors.extend(validate_name(command['command'], 'Command', 'commands'))
    # Validate the names and ranges of properties for the command
    for prop in command.get("properties", []):
        errors.extend(validate_name(prop['name'], 'Property', f"command '{command['command']}'"))
        # Check if a range exists and if so, validate it
        if "range" in prop:
            if not isinstance(prop["range"], list) or len(prop["range"]) != 2 or prop["range"][0] > prop["range"][1]:
                errors.append(f"Invalid range '{prop['range']}' in property '{prop['name']}' for command '{command['command']}'.")
    return errors

# Main function to validate the entire JSON
# 'commands_data' is a dictionary containing the JSON data
def validate_json(commands_data):
    """Validate error-code uniqueness and every command's fields and error references."""
    errors = []
    error_names = set()
    error_numbers = set()
    for error in commands_data.get('error_codes', []):
        name, code = error.get('name'), error.get('code')
        if not isinstance(name, str) or name == 'OK' or not re.fullmatch(r'[A-Z][A-Z0-9_]*', name):
            errors.append('Error names must be uppercase C identifiers.')
            continue
        if type(code) is not int or not 1 <= code <= 255:
            errors.append(f'Error {name} must have a nonzero uint8 code.')
            continue
        if name in error_names or code in error_numbers:
            errors.append(f'Duplicate error name or code: {name}.')
        error_names.add(name)
        error_numbers.add(code)
        if not error.get('description'):
            errors.append(f'Error {name} needs a description.')

    # Validate each command in the JSON
    for command in commands_data.get("commands", []):
        errors.extend(validate_command(command))
        declared = command.get('errors')
        if not isinstance(declared, list) or any(not isinstance(e, str) for e in declared):
            errors.append(f"Command {command['command']} must declare an errors array of names.")
        else:
            if len(declared) != len(set(declared)):
                errors.append(f"Command {command['command']} has duplicate errors.")
            for name in declared:
                if name not in error_names:
                    errors.append(f"Command {command['command']} references undefined error {name}.")
    return errors

# Generates a Markdown file from the commands JSON file
def generate_md_file(commands_data):
    """Render the command reference and per-command errors from the JSON schema."""
    md_content = "# Kinisi motor controller commands\n\n"

    # version
    md_content += f"Version: {commands_data['version']}\n"
    md_content += "---\n"
    if int(commands_data['version'].split('.')[0]) >= 2:
        md_content += "\nAll replies use `[length][command ID][message ID][payload]`. Failures use ERROR with the failed command ID and error code. Ordinary commands without a data response return an empty acknowledgment. Successful TIME_SYNC_RESPONSE messages receive no ACK; INIT additionally receives READY after clock setup (see [time sync](docs/time-sync.md)). See [shared response format and errors](docs/responses.md). Protocol 1.x clients require updates.\n"

    errors_by_name = {error['name']: error for error in commands_data.get('error_codes', [])}
    md_content += "\n## Error codes\n\nErrors use the shared ERROR message, echoing the request message ID and identifying the failed command. Each command below lists its possible errors. UNKNOWN_COMMAND applies to unrecognized or incorrectly directed messages.\n\n| Code | Name | Meaning |\n| --- | --- | --- |\n"
    for error in errors_by_name.values():
        md_content += f"| {error['code']} | `{error['name']}` | {error['description']} |\n"

    # Generate command definitions
    md_content += "\n## Commands\n"
    for command in commands_data.get("commands", []):
        md_content += f"### {command['command']} ({command['code']})\n"
        md_content += f"Direction: `{command['direction']}`\\\n"
        md_content += f"Description: {command['description']}\\\n"

        # Generate property definitions
        md_content += f"Properties:\n"
        cmd_props = command.get("properties", [])
        if len(cmd_props) != 0:
            for prop in cmd_props:
                md_content += f"- {prop['name']} ({prop.get('type', 'unknown')})"
                if "description" in prop:
                    md_content += f": {prop['description']}"
                md_content += "\n"
                if "range" in prop:
                    md_content += f"  - Range: {prop['range'][0]} to {prop['range'][1]}\n"
        else:
            md_content += "- None\n"

        # Generate response definition
        if "response" in command:
            response = command.get("response", [])
            md_content += f"Response (`{response['direction']}`):\n - {response['name']} ({response['type']}): {response['description']}\n"

        md_content += "\nErrors:\n\n"
        for name in command['errors']:
            error = errors_by_name[name]
            md_content += f"- `{name}` ({error['code']}): {error['description']}\n"
        if not command['errors']:
            md_content += "- None; this message does not receive an error reply in its declared direction.\n"

        md_content += "\n"
    return md_content


# Generates a C header file from the commands JSON file
def generate_c_header_file(commands_data):
    """Generate packed C wire types, error constants, and request validation helpers."""
    def get_type(type_name):
        """Translate schema booleans to explicit one-byte fields for packed C structs."""
        if type_name == 'bool':
            return 'uint8_t'
        return type_name
    
    def generate_objects(objects):
        """Render the shared response object definitions as packed C structs."""
        result = ""
        for obj in objects:
            result += f"// {obj['name']}: {obj['description']}\n"
            result += "#pragma pack(push, 1)\n"
            result += f"typedef struct\n"
            result += "{\n"
            for prop in obj.get("properties", []):
                result += f"    {get_type(prop['type'])} {prop['name']}; // {prop['description']}\n"
            result += f"}} {obj['name']};\n"
            result += "#pragma pack(pop)\n\n"
        return result
    
    # Create commands definitions
    definitions = "// Commands"
    for cmd in commands_data['commands']:
        definitions +=  f"// {cmd['description']}\n"
        symbol = "KINISI_MESSAGE_" + cmd['command'] if cmd['direction'] == 'controller_to_client' else cmd['command']
        definitions += f"#define {symbol} {cmd['code']}\n\n"

    commands_struct = "#pragma pack(push, 1)\n"
    commands_struct += "typedef struct\n"
    commands_struct += "{\n"
    commands_struct += "    uint8_t commandType;  //command type\n"
    commands_struct += "    uint16_t message_id; // Shared header, little-endian\n"
    commands_struct += "    union {   //Union to support different properties of each command\n"

    for cmd in commands_data['commands']:
        if cmd['direction'] == 'controller_to_client':
            continue
        commands_struct += f"        // {cmd['command']}: {cmd['description']}\n"
        commands_struct += "        struct {\n"
        for prop in cmd.get("properties", []):
            prop_type = get_type(prop['type'])
            commands_struct += f"            {prop_type} {prop['name']}; // {prop['description']}\n"
        commands_struct += f"        }} {cmd['command'].lower()};\n\n"

    commands_struct += "    } properties;\n"
    commands_struct += "} controller_command_t;\n"
    commands_struct += "#pragma pack(pop)\n\n"
    
    result = file_header(commands_data['version'])
    result += "#pragma once\n\n"
    result += "#include <stdint.h>\n\n"
    for error in commands_data.get('error_codes', []):
        result += f"#define RESPONSE_{error['name']} {error['code']}U // {error['description']}\n"
    result += "\n"
    for label, value in zip(('MAJOR', 'MINOR', 'PATCH'), commands_data['version'].split('.')):
        result += f"#define KINISI_PROTOCOL_{label} {int(value)}U\n"
    result += definitions
    result += "\n"
    result += generate_objects(commands_data['objects'])
    result += "\n"
    result += commands_struct

    result += "#include <stddef.h>\n#include <math.h>\n\n"
    result += "/**\n * @brief Return the accepted request size, including command and message ID.\n * @param command Incoming command ID.\n * @return Bytes excluding the length prefix, or zero for an unsupported direction/ID.\n */\n"
    result += "static inline size_t command_request_size(uint8_t command) {\n    switch (command) {\n"
    for cmd in commands_data['commands']:
        if cmd['direction'] == 'controller_to_client':
            continue
        size = 3 + sum(type_to_size_map[p['type']] for p in cmd.get('properties', []))
        result += f"    case {cmd['command']}: return {size}U;\n"
    result += "    default: return 0;\n    }\n}\n\n"
    result += "/**\n * @brief Check schema ranges, booleans, and finite numeric fields.\n * @param command Decoded request whose length has already been validated.\n * @return Nonzero for valid schema arguments; resource checks are performed separately.\n */\n"
    result += "static inline int command_arguments_valid(const controller_command_t *command) {\n    switch (command->commandType) {\n"
    for cmd in commands_data['commands']:
        if cmd['direction'] == 'controller_to_client':
            continue
        checks = []
        for prop in cmd.get('properties', []):
            value = f"command->properties.{cmd['command'].lower()}.{prop['name']}"
            if prop['type'] == 'double':
                checks.append(f"isfinite({value})")
            if prop['type'] == 'bool':
                checks.append(f"{value} <= 1U")
            if 'range' in prop:
                low, high = prop['range']
                if low != 0 or not prop['type'].startswith('uint'):
                    checks.append(f"{value} >= {low}")
                checks.append(f"{value} <= {high}")
        result += f"    case {cmd['command']}: return " + (' && '.join(checks) or '1') + ";\n"
    result += "    default: return 0;\n    }\n}\n"

    return result

# Generates C++ code from the commands JSON file
def generate_cpp_code(commands_data):
    # Create commands definitions
    """Generate the C++ command wrapper text for client-to-controller messages."""
    definitions = "// Commands"
    for cmd in commands_data['commands']:
        definitions +=  f"// {cmd['description']}\n"
        symbol = "KINISI_MESSAGE_" + cmd['command'] if cmd['direction'] == 'controller_to_client' else cmd['command']
        definitions += f"#define {symbol} {cmd['code']}\n\n"

    commands_class = "// Commands class\n"
    commands_class += "class KinisiCommands {\n"
    commands_class += "public:\n"
    commands_class += "    virtual int read(unsigned int lenght) = 0;\n\n"
    commands_class += "    virtual int write(unsigned char* cmd, unsigned int size) = 0;\n\n"

    # Generate class method for each command
    commands_class += "public:\n"
    for cmd in commands_data['commands']:
        if cmd['direction'] == 'controller_to_client':
            continue
        commands_class += f"    // {cmd['command']}: {cmd['description']}\n"
        func_args = ', '.join([f"{prop['type']} {prop['name']}" for prop in cmd.get('properties', [])])
        commands_class += f"    void {cmd['command'].lower()}({func_args}){{\n"
        commands_class += f"        unsigned char cmd[] = {{ 0, {cmd['command']}, {', '.join([prop['name'] for prop in cmd.get('properties', [])])}}};\n"
        commands_class += f"        cmd[0] = sizeof(cmd) - 1;\n"
        commands_class += f"        write(cmd, sizeof(cmd));\n"
        # Generate response 
        if "response" in cmd:
            response = cmd.get("response", [])
            commands_class += f"        return read(typeof({response['type']}));\n"
        commands_class += "    }\n"
    commands_class += "};\n\n"

    # Put everything together
    result = file_header(commands_data['version'])
    result += "#pragma once\n\n"
    result += "#include <stdint.h>\n\n"
    result += "\n"
    result += definitions
    result += "\n"
    result += commands_class

    return result

# Converts a string with underscores into PascalCase:
def to_pascal(s):
    """Convert an underscore-separated identifier to PascalCase."""
    return ''.join(word.capitalize() for word in s.split('_'))

def main():
    """Run the command-line schema generator and report validation failures."""
    parser = argparse.ArgumentParser(description='Generate code from command definitions in JSON.')
    parser.add_argument('input_json_path', type=str, help='Path to the input JSON file containing command definitions.')
    parser.add_argument('output_path', type=str, help='Path to the output file.')
    parser.add_argument('--language', type=str, default='js', choices=['c','cpp', 'md'], help='Programming language for the generated code.')

    args = parser.parse_args()

    # Check if the input JSON file exists
    if not os.path.exists(args.input_json_path):
        print(f"Error: Input JSON file '{args.input_json_path}' not found.")
        return

    try:
        with open(args.input_json_path, 'r') as file:
            commands_data = json.load(file)
    except json.JSONDecodeError:
        print("Error: Could not decode the input JSON file.")
        return
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return

    validation_errors = validate_json(commands_data)
    if validation_errors:
        print("Validation errors found:")
        for error in validation_errors:
            print(f"- {error}")
        raise SystemExit(1)

    generated_code = ""
    if args.language == 'c':
        generated_code = generate_c_header_file(commands_data)
    elif args.language == 'cpp':
        generated_code = generate_cpp_code(commands_data)
    elif args.language == 'md':
        generated_code = generate_md_file(commands_data)
    else:
        print("Error: Unsupported programming language.")
        return

    try:
        with open(args.output_path, 'w') as file:
            file.write(generated_code)
    except Exception as e:
        print(f"An error occurred while writing to the output file: {e}")
        return

    print(f"{args.language.upper()} code has been generated and saved to {args.output_path}")

if __name__ == "__main__":
    main()
