// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2023-09-18 20:20:00
// Version: 1.0.0
// ----------------------------------------------------------------------------

#pragma once

#include <stdint.h>

// Commands// This command initializes a motor and prepares it for use.
#define INITIALIZE_MOTOR 0x01

// This command sets the speed of the specified motor.
#define SET_MOTOR_SPEED 0x02

// This command sets the controller for the specified motor.
#define INITIALIZE_MOTOR_CONTROLLER 0x03

// This command sets the target velocity for the specified motor.
#define SET_MOTOR_TARGET_VELOCITY 0x04

// This command deletes the controller for the specified motor.
#define DELETE_MOTOR_CONTROLLER 0x05

// This command initializes an encoder and prepares it for use.
#define INITIALIZE_ENCODER 0x11

// This command retrieves the current value of the encoder.
#define GET_ENCODER_VALUE 0x12

// This command sets the specified pin to a low state.
#define SET_PIN_LOW 0x20

// This command sets the specified pin to a high state.
#define SET_PIN_HIGH 0x21

// This command toggles the specified pin.
#define TOGGLE_PIN 0x22

// This command turns off the status LED.
#define SET_STATUS_LED_OFF 0x23

// This command turns on the status LED.
#define SET_STATUS_LED_ON 0x24

// This command toggles the status LED.
#define TOGGLE_STATUS_LED 0x25

// This command initializes the platform and prepares it for use.
#define INITIALIZE_PLATFORM 0x30

// This command sets the velocity input for the platform.
#define SET_PLATFORM_VELOCITY_INPUT 0x31

// This command sets the controller for the platform.
#define SET_PLATFORM_CONTROLLER 0x32


#pragma pack(push, 1)
typedef struct
{
    uint8_t commandType;  //command type
    union {   //Union to support different properties of each command
        // INITIALIZE_MOTOR: This command initializes a motor and prepares it for use.
        struct {
            uint8_t motor_index; // The index of the motor to initialize.
        } initialize_motor;

        // SET_MOTOR_SPEED: This command sets the speed of the specified motor.
        struct {
            uint8_t motor_index; // The index of the motor to set the speed for.
            uint8_t direction; // The direction of the motor.
            uint16_t speed; // The speed of the motor.
        } set_motor_speed;

        // INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor.
        struct {
            uint8_t motor_index; // The index of the motor to set the controller for.
            double kp; // Proportional constant of PID
            double ki; // Integral constant of PID
            double kd; // Derivative constant of PID
        } initialize_motor_controller;

        // SET_MOTOR_TARGET_VELOCITY: This command sets the target velocity for the specified motor.
        struct {
            uint8_t motor_index; // The index of the motor to set the target velocity for.
            uint8_t direction; // The direction of the motor.
            uint16_t speed; // The speed of the motor.
        } set_motor_target_velocity;

        // DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor.
        struct {
            uint8_t motor_index; // The index of the motor to delete the controller for.
        } delete_motor_controller;

        // INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
        struct {
            uint8_t encoder_index; // The index of the encoder to initialize.
        } initialize_encoder;

        // GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to retrieve the value for.
        } get_encoder_value;

        // SET_PIN_LOW: This command sets the specified pin to a low state.
        struct {
            uint8_t pin_number; // The number of the pin to set to a low state.
        } set_pin_low;

        // SET_PIN_HIGH: This command sets the specified pin to a high state.
        struct {
            uint8_t pin_number; // The number of the pin to set to a high state.
        } set_pin_high;

        // TOGGLE_PIN: This command toggles the specified pin.
        struct {
            uint8_t pin_number; // The number of the pin to toggle.
        } toggle_pin;

        // SET_STATUS_LED_OFF: This command turns off the status LED.
        struct {
        } set_status_led_off;

        // SET_STATUS_LED_ON: This command turns on the status LED.
        struct {
        } set_status_led_on;

        // TOGGLE_STATUS_LED: This command toggles the status LED.
        struct {
        } toggle_status_led;

        // INITIALIZE_PLATFORM: This command initializes the platform and prepares it for use.
        struct {
        } initialize_platform;

        // SET_PLATFORM_VELOCITY_INPUT: This command sets the velocity input for the platform.
        struct {
            int8_t x; // X component of platform velocity input.
            int8_t y; // Y component of platform velocity input.
            int8_t t; // Theta component of platform velocity input.
        } set_platform_velocity_input;

        // SET_PLATFORM_CONTROLLER: This command sets the controller for the platform.
        struct {
        } set_platform_controller;

    } properties;
} controller_command_t;
#pragma pack(pop)

