// ----------------------------------------------------------------------------
// Kinisi motr controller commands.
// This file is auto generated by the commands generator from JSON file.
// Do not edit this file manually.
// Timestamp: 2026-07-30 20:16:00
// Version: 1.4.0
// ----------------------------------------------------------------------------

#pragma once

#include <stdint.h>

// Commands// This command initializes a motor and prepares it for use. Ignored if the motor is currently owned by an active platform (one of its wheels), so platform wheels are not reconfigured out from under the platform.
#define INITIALIZE_MOTOR 0x01

// This command sets the speed of the specified motor in PWM. Ignored if the motor is currently owned by an active platform (one of its wheels); use the platform velocity commands to drive platform wheels.
#define SET_MOTOR_SPEED 0x02

// Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor terminals open (high impedance) so it free-wheels and spins down gradually under its own friction. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to stop a platform, use STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold position and stop quickly.
#define STOP_MOTOR 0x03

// Actively brakes the motor (short brake): both H-bridge outputs are driven high, shorting the motor terminals together so the motor's own back-EMF resists rotation and it stops quickly and holds position. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to brake a platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead. Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast freely instead.
#define BRAKE_MOTOR 0x04

// This command sets the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels), so it cannot create a competing controller on a platform wheel.
#define INITIALIZE_MOTOR_CONTROLLER 0x05

// This command sets the target speed for the specified motor in radians. Ignored if the motor is currently owned by an active platform (one of its wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.
#define SET_MOTOR_TARGET_SPEED 0x06

// This command resets the closed-loop controller for the specified motor: it clears the accumulated PID state (integrator windup, derivative history and internal output) and re-zeros the target speed, while keeping the controller running with its existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a motor cleanly to a stop without deleting and re-initializing the controller. No effect if no controller is running for that motor, and ignored if the motor is currently owned by an active platform (one of its wheels).
#define RESET_MOTOR_CONTROLLER 0x07

// This command gets the state of the controller for the specified motor.
#define GET_MOTOR_CONTROLLER_STATE 0x08

// This command deletes the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.
#define DELETE_MOTOR_CONTROLLER 0x09

// This command sets the global update frequency (in Hz) of the closed-loop motor controller task. All motor controllers share a single control loop, so this frequency is global and affects every currently running controller as well as any created afterwards; the PID sampling time is updated to match. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 10 Hz (100 ms) at start-up.
#define SET_CONTROLLER_FREQUENCY 0x0A

// This command retrieves the current global update frequency (in Hz) of the closed-loop motor controller task.
#define GET_CONTROLLER_FREQUENCY 0x0B

// This command initializes an encoder and prepares it for use.
#define INITIALIZE_ENCODER 0x11

// This command retrieves the current value of the encoder.
#define GET_ENCODER_VALUE 0x12

// This command starts the odometry calculation for the specified encoder.
#define START_ENCODER_ODOMETRY 0x13

// This command resets the odometry calculation for the specified encoder.
#define RESET_ENCODER_ODOMETRY 0x14

// This command stops the odometry calculation for the specified encoder.
#define STOP_ENCODER_ODOMETRY 0x15

// This command retrieves the odometry of the specified encoder.
#define GET_ENCODER_ODOMETRY 0x16

// This command sets the global update frequency (in Hz) of the odometry task. A single odometry task integrates all encoder and platform odometry, so this frequency is global. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at start-up.
#define SET_ODOMETRY_FREQUENCY 0x17

// This command retrieves the current global update frequency (in Hz) of the odometry task.
#define GET_ODOMETRY_FREQUENCY 0x18

// This command initializes a digital pin and prepares it for use.
#define INITIALIZE_GPIO_PIN 0x20

// This command sets the specified pin to a state.
#define SET_GPIO_PIN_STATE 0x21

// This command gets the state of the specified pin.
#define GET_GPIO_PIN_STATE 0x22

// This command toggles the specified pin.
#define TOGGLE_GPIO_PIN_STATE 0x23

// This command sets the status LED to a state.
#define SET_STATUS_LED_STATE 0x25

// This command toggles the status LED.
#define TOGGLE_STATUS_LED_STATE 0x26

// This command initializes a mecanum (4-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots are occupied by this platform.
#define INITIALIZE_MECANUM_PLATFORM 0x30

// This command initializes an omni (3-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used by this platform and stays free for other purposes.
#define INITIALIZE_OMNI_PLATFORM 0x31

// This command initializes a differential (2-wheel) platform and prepares it for use. It uses motor and encoder index 0 for the left wheel and index 1 for the right wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1 parameters. Motor indices 2 and 3 are not used by this platform and stay free for other purposes.
#define INITIALIZE_DIFFERENTIAL_PLATFORM 0x32

// This command sets the velocity for the platform in PWM.
#define SET_PLATFORM_VELOCITY 0x40

// This command sets the controller for the platform.
#define START_PLATFORM_CONTROLLER 0x41

// This command set the target velocity for the platform in meters per second.
#define SET_PLATFORM_TARGET_VELOCITY 0x42

// This command gets the current velocity of the platform in meters per second.
#define GET_PLATFORM_CURRENT_VELOCITY 0x43

// This command stops the controller for the platform.
#define STOP_PLATFORM_CONTROLLER 0x44

// This command starts the odometry calculation for the platform.
#define START_PLATFORM_ODOMETRY 0x45

// This command resets the odometry calculation for the platform.
#define RESET_PLATFORM_ODOMETRY 0x46

// This command stops the odometry calculation for the platform.
#define STOP_PLATFORM_ODOMETRY 0x47

// This command retrieves the odometry of the platform in meters and radians.
#define GET_PLATFORM_ODOMETRY 0x48

// This command actively brakes all of this platform's wheel motors (short brake) so they resist motion and hold position, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors resist motion until a new command is issued.
#define BRAKE_PLATFORM 0x49

// This command lets all of this platform's wheel motors coast freely (high impedance) so they spin down without resistance, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors spin down without resistance.
#define COAST_PLATFORM 0x4A


// motor_controller_state: The state of the controller for the specified motor.
#pragma pack(push, 1)
typedef struct
{
    int8_t motor_index; // Index of the motor with the controller.
    double kp; // Proportional constant of PID
    double ki; // Integral constant of PID
    double kd; // Derivative constant of PID
    double target_speed; // The target speed of the motor.
    double current_speed; // The current speed of the motor.
    double error; // The error of the motor.
    double output; // The output of the motor.
} motor_controller_state;
#pragma pack(pop)

// platform_velocity: The velocity of the platform in meters per second.
#pragma pack(push, 1)
typedef struct
{
    double x; // X component of platform velocity in meters per second
    double y; // Y component of platform velocity in meters per second
    double t; // Theta component of platform velocity in radians per second
} platform_velocity;
#pragma pack(pop)

// platform_odometry: The odometry of the platform in meters and radians.
#pragma pack(push, 1)
typedef struct
{
    double x; // X component of platform odometry in meters
    double y; // Y component of platform odometry in meters
    double t; // Theta component of platform odometry in radians
} platform_odometry;
#pragma pack(pop)


#pragma pack(push, 1)
typedef struct
{
    uint8_t commandType;  //command type
    union {   //Union to support different properties of each command
        // INITIALIZE_MOTOR: This command initializes a motor and prepares it for use. Ignored if the motor is currently owned by an active platform (one of its wheels), so platform wheels are not reconfigured out from under the platform.
        struct {
            uint8_t motor_index; // The index of the motor to initialize.
            uint8_t is_reversed; // Whether or not the motor is reversed.
        } initialize_motor;

        // SET_MOTOR_SPEED: This command sets the speed of the specified motor in PWM. Ignored if the motor is currently owned by an active platform (one of its wheels); use the platform velocity commands to drive platform wheels.
        struct {
            uint8_t motor_index; // The index of the motor to set the speed for.
            double pwm; // The speed of the motor.
        } set_motor_speed;

        // STOP_MOTOR: Coasts the motor to a stop: both H-bridge outputs are driven low, leaving the motor terminals open (high impedance) so it free-wheels and spins down gradually under its own friction. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to stop a platform, use STOP_PLATFORM_CONTROLLER, COAST_PLATFORM or BRAKE_PLATFORM instead. Use STOP_MOTOR for a soft, low-stress stop; use BRAKE_MOTOR when you need the motor to hold position and stop quickly.
        struct {
            uint8_t motor_index; // The index of the motor to set the speed for.
        } stop_motor;

        // BRAKE_MOTOR: Actively brakes the motor (short brake): both H-bridge outputs are driven high, shorting the motor terminals together so the motor's own back-EMF resists rotation and it stops quickly and holds position. This also stops that motor's closed-loop speed controller if one is running (started via INITIALIZE_MOTOR_CONTROLLER), so the PID loop cannot re-drive the motor; to command the motor by target speed again you must re-initialize its controller. This is a single-motor command and is ignored if the motor is currently owned by an active platform (one of its wheels); to brake a platform, use BRAKE_PLATFORM (or STOP_PLATFORM_CONTROLLER / COAST_PLATFORM) instead. Use BRAKE_MOTOR for a fast, holding stop; use STOP_MOTOR to let the motor coast freely instead.
        struct {
            uint8_t motor_index; // The index of the motor to set the speed for.
        } brake_motor;

        // INITIALIZE_MOTOR_CONTROLLER: This command sets the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels), so it cannot create a competing controller on a platform wheel.
        struct {
            uint8_t motor_index; // The index of the motor to set the controller for.
            uint8_t is_reversed; // Whether or not the motor is reversed.
            uint8_t encoder_index; // The index of the encoder to use for the controller.
            uint8_t is_encoder_reversed; // Reverses the encoder counting direction, independently of the motor's is_reversed. For closed-loop control the encoder must report a positive measured speed when a positive speed is commanded (negative feedback); if the controller runs away, flip this flag.
            double encoder_resolution; // Encoder resolution in ticks per revolution. The value can not be negative or zero.
            double kp; // Proportional constant of PID
            double ki; // Integral constant of PID
            double kd; // Derivative constant of PID
            double integral_limit; // Integral limit of PID controller. The value can not be negative or zero. If the value is zero or negative, the integral limit is disabled.
        } initialize_motor_controller;

        // SET_MOTOR_TARGET_SPEED: This command sets the target speed for the specified motor in radians. Ignored if the motor is currently owned by an active platform (one of its wheels); use SET_PLATFORM_TARGET_VELOCITY to drive platform wheels.
        struct {
            uint8_t motor_index; // The index of the motor to set the target velocity for.
            double speed; // The speed of the motor.
        } set_motor_target_speed;

        // RESET_MOTOR_CONTROLLER: This command resets the closed-loop controller for the specified motor: it clears the accumulated PID state (integrator windup, derivative history and internal output) and re-zeros the target speed, while keeping the controller running with its existing tuning (kp/ki/kd). Use it to recover from integrator windup or to bring a motor cleanly to a stop without deleting and re-initializing the controller. No effect if no controller is running for that motor, and ignored if the motor is currently owned by an active platform (one of its wheels).
        struct {
            uint8_t motor_index; // The index of the motor to reset the controller for.
        } reset_motor_controller;

        // GET_MOTOR_CONTROLLER_STATE: This command gets the state of the controller for the specified motor.
        struct {
            uint8_t motor_index; // The index of the motor to get the state for.
        } get_motor_controller_state;

        // DELETE_MOTOR_CONTROLLER: This command deletes the controller for the specified motor. Ignored if the motor is currently owned by an active platform (one of its wheels); use STOP_PLATFORM_CONTROLLER to stop the platform controller instead.
        struct {
            uint8_t motor_index; // The index of the motor to delete the controller for.
        } delete_motor_controller;

        // SET_CONTROLLER_FREQUENCY: This command sets the global update frequency (in Hz) of the closed-loop motor controller task. All motor controllers share a single control loop, so this frequency is global and affects every currently running controller as well as any created afterwards; the PID sampling time is updated to match. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 10 Hz (100 ms) at start-up.
        struct {
            uint16_t frequency; // The controller update frequency in Hz. Valid range 1 to 1000 Hz; values outside are clamped, and 0 is ignored.
        } set_controller_frequency;

        // GET_CONTROLLER_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the closed-loop motor controller task.
        struct {
        } get_controller_frequency;

        // INITIALIZE_ENCODER: This command initializes an encoder and prepares it for use.
        struct {
            uint8_t encoder_index; // The index of the encoder to initialize.
            double encoder_resolution; // Encoder resolution in ticks per revolution. The value can not be negative or zero.
            uint8_t is_reversed; // Whether or not the encoder is reversed.
        } initialize_encoder;

        // GET_ENCODER_VALUE: This command retrieves the current value of the encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to retrieve the value for.
        } get_encoder_value;

        // START_ENCODER_ODOMETRY: This command starts the odometry calculation for the specified encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to start the odometry calculation for.
        } start_encoder_odometry;

        // RESET_ENCODER_ODOMETRY: This command resets the odometry calculation for the specified encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to reset the odometry calculation for.
        } reset_encoder_odometry;

        // STOP_ENCODER_ODOMETRY: This command stops the odometry calculation for the specified encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to stop the odometry calculation for.
        } stop_encoder_odometry;

        // GET_ENCODER_ODOMETRY: This command retrieves the odometry of the specified encoder.
        struct {
            uint8_t encoder_index; // The index of the encoder to retrieve the odometry for.
        } get_encoder_odometry;

        // SET_ODOMETRY_FREQUENCY: This command sets the global update frequency (in Hz) of the odometry task. A single odometry task integrates all encoder and platform odometry, so this frequency is global. The requested value is clamped to the supported range of 1 to 1000 Hz (the 1000 Hz maximum is bounded by the 1 ms RTOS tick). The value is then quantized to the 1 ms RTOS tick (period_ms = 1000 / frequency), so effective frequencies are 1000/N Hz. A value of 0 is invalid and ignored. Defaults to 20 Hz (50 ms) at start-up.
        struct {
            uint16_t frequency; // The odometry update frequency in Hz. Valid range 1 to 1000 Hz; values outside are clamped, and 0 is ignored.
        } set_odometry_frequency;

        // GET_ODOMETRY_FREQUENCY: This command retrieves the current global update frequency (in Hz) of the odometry task.
        struct {
        } get_odometry_frequency;

        // INITIALIZE_GPIO_PIN: This command initializes a digital pin and prepares it for use.
        struct {
            uint8_t pin_number; // The number of the pin to initialize.
            uint8_t mode; // Set digital pin as input or output. Modes: 0 = INPUT_PULLDOWN, 1 = INPUT_PULLUP, 2 = INPUT_NOPULL, 3 = OUTPUT.
        } initialize_gpio_pin;

        // SET_GPIO_PIN_STATE: This command sets the specified pin to a state.
        struct {
            uint8_t pin_number; // The number of the pin to set to a state.
            uint8_t state; // The state of the pin. 0 = LOW, 1 = HIGH.
        } set_gpio_pin_state;

        // GET_GPIO_PIN_STATE: This command gets the state of the specified pin.
        struct {
            uint8_t pin_number; // The number of the pin to get the state for.
        } get_gpio_pin_state;

        // TOGGLE_GPIO_PIN_STATE: This command toggles the specified pin.
        struct {
            uint8_t pin_number; // The number of the pin to toggle.
        } toggle_gpio_pin_state;

        // SET_STATUS_LED_STATE: This command sets the status LED to a state.
        struct {
            uint8_t state; // The state of the status LED. 0 = OFF, 1 = ON.
        } set_status_led_state;

        // TOGGLE_STATUS_LED_STATE: This command toggles the status LED.
        struct {
        } toggle_status_led_state;

        // INITIALIZE_MECANUM_PLATFORM: This command initializes a mecanum (4-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1, 2 and 3 (one per wheel), which correspond to the is_reversed_0..3 and is_encoder_reversed_0..3 parameters. All four motor slots are occupied by this platform.
        struct {
            uint8_t is_reversed_0; // Determines if motor 0 is reversed.
            uint8_t is_reversed_1; // Determines if motor 1 is reversed.
            uint8_t is_reversed_2; // Determines if motor 2 is reversed.
            uint8_t is_reversed_3; // Determines if motor 3 is reversed.
            uint8_t is_encoder_reversed_0; // Reverses encoder 0 counting direction, independently of motor 0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_1; // Reverses encoder 1 counting direction, independently of motor 1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_2; // Reverses encoder 2 counting direction, independently of motor 2's is_reversed_2. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_3; // Reverses encoder 3 counting direction, independently of motor 3's is_reversed_3. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            double length; // Length of the platform in meters.
            double width; // Width of the platform in meters.
            double wheels_diameter; // Diameter of the robot wheels in meters.
            double encoder_resolution; // Encoder resolution in ticks per revolution. The value can not be negative. If platform does not have encoders, the value should be set to zero.
        } initialize_mecanum_platform;

        // INITIALIZE_OMNI_PLATFORM: This command initializes an omni (3-wheel) platform and prepares it for use. It uses motor and encoder indices 0, 1 and 2 (one per wheel), which correspond to the is_reversed_0..2 and is_encoder_reversed_0..2 parameters. Motor index 3 is not used by this platform and stays free for other purposes.
        struct {
            uint8_t is_reversed_0; // Determines if motor 0 is reversed.
            uint8_t is_reversed_1; // Determines if motor 1 is reversed.
            uint8_t is_reversed_2; // Determines if motor 2 is reversed.
            uint8_t is_encoder_reversed_0; // Reverses encoder 0 counting direction, independently of motor 0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_1; // Reverses encoder 1 counting direction, independently of motor 1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_2; // Reverses encoder 2 counting direction, independently of motor 2's is_reversed_2. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            double wheels_diameter; // Diameter of the robot wheels in millimeters.
            double robot_radius; // Distance berween the center of the robot and the center of the wheels in millimeters.
            double encoder_resolution; // Encoder resolution in ticks per revolution. The value can not be negative. If platform does not have encoders, the value should be set to zero.
        } initialize_omni_platform;

        // INITIALIZE_DIFFERENTIAL_PLATFORM: This command initializes a differential (2-wheel) platform and prepares it for use. It uses motor and encoder index 0 for the left wheel and index 1 for the right wheel, which correspond to the is_reversed_0/1 and is_encoder_reversed_0/1 parameters. Motor indices 2 and 3 are not used by this platform and stay free for other purposes.
        struct {
            uint8_t is_reversed_0; // Determines if motor 0 is reversed.
            uint8_t is_reversed_1; // Determines if motor 1 is reversed.
            uint8_t is_encoder_reversed_0; // Reverses encoder 0 counting direction, independently of motor 0's is_reversed_0. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            uint8_t is_encoder_reversed_1; // Reverses encoder 1 counting direction, independently of motor 1's is_reversed_1. Set so the closed-loop feedback is negative (flip if the wheel runs away when given a target speed).
            double wheel_diameter; // Diameter of the robot wheels in meters.
            double wheel_base; // Distance between the two wheels in meters.
            double encoder_resolution; // Encoder resolution in ticks per revolution. The value can not be negative. If platform does not have encoders, the value should be set to zero.
        } initialize_differential_platform;

        // SET_PLATFORM_VELOCITY: This command sets the velocity for the platform in PWM.
        struct {
            double x; // X component of platform velocity in PWM
            double y; // Y component of platform velocity in PWM
            double t; // Theta component of platform velocity in PWM
        } set_platform_velocity;

        // START_PLATFORM_CONTROLLER: This command sets the controller for the platform.
        struct {
            double kp; // Proportional constant of PID
            double ki; // Integral constant of PID
            double kd; // Derivative constant of PID
            double integral_limit; // Integral limit of PID controller. The value can not be negative or zero. If the value is zero or negative, the integral limit is disabled.
        } start_platform_controller;

        // SET_PLATFORM_TARGET_VELOCITY: This command set the target velocity for the platform in meters per second.
        struct {
            double x; // X component of platform velocity in meters per second
            double y; // Y component of platform velocity in meters per second
            double t; // Theta component of platform velocity in radians per second
        } set_platform_target_velocity;

        // GET_PLATFORM_CURRENT_VELOCITY: This command gets the current velocity of the platform in meters per second.
        struct {
        } get_platform_current_velocity;

        // STOP_PLATFORM_CONTROLLER: This command stops the controller for the platform.
        struct {
        } stop_platform_controller;

        // START_PLATFORM_ODOMETRY: This command starts the odometry calculation for the platform.
        struct {
        } start_platform_odometry;

        // RESET_PLATFORM_ODOMETRY: This command resets the odometry calculation for the platform.
        struct {
        } reset_platform_odometry;

        // STOP_PLATFORM_ODOMETRY: This command stops the odometry calculation for the platform.
        struct {
        } stop_platform_odometry;

        // GET_PLATFORM_ODOMETRY: This command retrieves the odometry of the platform in meters and radians.
        struct {
        } get_platform_odometry;

        // BRAKE_PLATFORM: This command actively brakes all of this platform's wheel motors (short brake) so they resist motion and hold position, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors resist motion until a new command is issued.
        struct {
        } brake_platform;

        // COAST_PLATFORM: This command lets all of this platform's wheel motors coast freely (high impedance) so they spin down without resistance, and stops the platform velocity controller if it is running (you must call START_PLATFORM_CONTROLLER again to resume closed-loop platform control). Motors used outside this platform are not affected. The motors spin down without resistance.
        struct {
        } coast_platform;

    } properties;
} controller_command_t;
#pragma pack(pop)

